### ISSUE TITLE
Spotify not working

### ISSUE THREAD

**Issue by meiser79** [RoggerFabri/mopidy-icesnap#52]
Hi,

thanks a lot for your docker images! I'd like to use the Spotify extension, but in the Iris webinterface, it shows "Mopidy-Spotify extension is not running - you will not be able to play any Spotify tracks".
Both Mopidy-Spotify and Iris are authenticated via the Spotify API.

Could you please give some advice how to get it running?

May I suggest to use the APT packages as described at https://docs.mopidy.com/stable/installation/debian/?

Thanks,
meiser

**Comment by RoggerFabri** [comment]
Hey friend, glad you find the image useful 👍🏻 

I have [commented out](https://github.com/RoggerFabri/mopidy-icesnap/blob/master/mopidy/Dockerfile#L19) the Mopidy-Spotify extension in my custom `mopidy` image a while ago, and I have started worked on a fork since the deprecation of `libspotify`. The deprecation broke the Mopidy-Spotify extension, and there's no release with the fix implemented yet (https://github.com/mopidy/mopidy-spotify/issues/110).

I gave up using it for a while as it is a WIP, so things are constantly broken, whenever I want to listen on multi-room speakers I'm using `raspotify` instead (from [here](https://github.com/RoggerFabri/mopidy-icesnap/blob/master/snapserver/Dockerfile#L17)), which is baked in into my `snapserver` image, completely bypassing Mopidy.

There is an image which was working a while ago which I forked my new repository from, you can find it [here](https://github.com/jojo141185/mopidy-docker). But as I said, since this is WIP I completely parked Mopidy + Spotify for a while until the whole integration is fixed with a new release of the extension.

**Comment by meiser79** [comment]
Thanks for all the info, very much appreciated.

As I understand, you might need to install Mopidy-Spotify==5.0.0a2, even though this does not help with the authentication issue happening in librespot currently.

But I will definitely have a look at your snapcast/snapserver docker images.

**Comment by RoggerFabri** [comment]
> As I understand, you might need to install Mopidy-Spotify==5.0.0a2

Humm this is cool, I will try building with this version, and I'll let you know how it goes. Have you tried this somehow and got it to work?

**Comment by RoggerFabri** [comment]
I can't get it to work and I'm getting the error outlined on this issue here:
- https://github.com/mopidy/mopidy-spotify/issues/388

**Comment by meiser79** [comment]
So you installed Mopidy-Spotify==5.0.0a2 and gst-plugin-spotify from https://github.com/kingosticks/gst-plugins-rs-build/releases?
I followed [this](https://github.com/mopidy/mopidy-spotify/issues/394#issuecomment-2285831264) steps on my laptop, mainly:
apt-get update
apt-get install git
curl https://sh.rustup.rs -sSf | sh
git clone https://github.com/kingosticks/librespot.git
cd librespot
git checkout origin/credentials_with_access_token
cargo run --no-default-features -- --cache . --token ""

Opened the mentioned link on my laptop and granted access. Then I copied the credentials.json into the /mopidy/config/data folder.

Could you update the docker image to install the above mentioned Mopidy-Spotify==5.0.0a2 and gst-plugin-spotify? As it gets lost if I start the docker container again.

I'm attaching my librespot binary just in case you don't want to compile it on your own.
[librespot.zip](https://github.com/user-attachments/files/16662328/librespot.zip)

**Comment by RoggerFabri** [comment]
I see, looks like a lot of stuff progressed since the last time I looked into this. I'll have a look at what you sent above and get back to you.

**Comment by meiser79** [comment]
Could you also migrate to "FROM debian:12-slim" in the Dockerfile?

**Comment by meiser79** [comment]
OK, got it to work, I had to downgrade libshout3 to version 2.4.1 using https://packages.debian.org/buster/libshout3

**Comment by RoggerFabri** [comment]
Was that using my image? If you guide me through everything you've done, I can reflect that on the Dockerfile.

**Comment by meiser79** [comment]
Yes, sure, I used your image.

What I've done:
pip install Mopidy-Spotify==5.0.0a2
wget https://github.com/kingosticks/gst-plugins-rs-build/releases/download/gst-plugin-spotify_0.12.2-1/gst-plugin-spotify_0.12.2-1_amd64.deb
dpkg -i gst-plugin-spotify_0.12.2-1_amd64.deb
wget http://ftp.de.debian.org/debian/pool/main/libs/libshout/libshout3_2.4.1-2_amd64.deb
dpkg -i libshout3_2.4.1-2_amd64.deb

**Comment by RoggerFabri** [comment]
I have pushed the images, and they are already on DockerHub, however I don't have an easy way to test them myself now, I'm still setting up the steps you mentioned [here](https://github.com/RoggerFabri/mopidy-icesnap/issues/52#issuecomment-2296858604) in order to have the `credentials.json`. Anyway, if you want to give it a try, images are pushed :)
